### ISSUE TITLE
Energy Meter 2 values to low

### ISSUE THREAD

**Issue by Kurisutian** [littleyoda/ha-pysmaplus#1]
I just compared the values for the energy meter 2 I'm using between this addon, the HA SMA Energy Meter(https://github.com/kellerza/hassio-sma-em) and the Web frontend from the device itself and it seems like the values coming in from this extension are generally lower than the others while the HA Addon and the actual device seem to be closer to the truth (with a certain delay). So somehow it seems that the values here are always lower.

**Comment by littleyoda** [comment]
can confirm the problem.
I will let you know when I have corrected it
