### ISSUE TITLE
Losing connection out of the blue

### ISSUE THREAD

**Issue by frederikvoGIT** [littleyoda/ha-pysmaplus#11]
Used Version of Home Assistant: 2024.7
Used Version of ha-pysmaplus: 0.3.6

Issue: last week the connection between HA and the inverter got lost out of the blue. 
First time i got the connection working again simply by clicking on "reload"
But yesterday by inorganic he only reconnected after 12hours of trying to reconnecting from time to time. 

I have the error.log- file  available but am unable to attach it because of the file size (50mb)

[config_entry-pysmaplus-247237495fd75ab1eff8383a337fa6ee(1).json](https://github.com/user-attachments/files/16383857/config_entry-pysmaplus-247237495fd75ab1eff8383a337fa6ee.1.json)

**Comment by littleyoda** [comment]
should be fixed by the latest version
