### ISSUE TITLE
SMA Tripower Einrichtung

### ISSUE THREAD

**Issue by alexraven1970** [littleyoda/ha-pysmaplus#12]
Hi,
ich schreib mal auf deutsch, hoffe das ist nicht gegen die etikette...
Ich bekomm meinen Wechselrichter nicht in HA

**Used Interface/Access Method**
Speedwire: [ x ]

![Bildschirmfoto vom 2024-07-28 12-35-02](https://github.com/user-attachments/assets/b23b6d10-9cd5-4ca1-9bc8-2a2914972cdf)

![Bildschirmfoto vom 2024-07-28 12-35-24](https://github.com/user-attachments/assets/b312cd10-cc68-4063-a2b9-f9ca47115c9d)

![Bildschirmfoto vom 2024-07-28 12-31-57](https://github.com/user-attachments/assets/b30b534a-56a4-4f68-95ee-551e6f1b76e7)

Was mach ich falsch?

**Comment by littleyoda** [comment]
Hi

kannst du bitte einmal die Debug-Protokollierung auf der Integrationseite aktivieren?
Danach Home Assistant neu starten
Wenn Home Assistant wieder hochgefahren ist, Debug Protokollierung abschalten.

Die Datei, die dann herruntergeladen wird, bitte einmal an mich schicken.
https://littleyoda.github.io/


![grafik](https://github.com/user-attachments/assets/6f6513c2-c897-44d0-8c2c-87977a762e36)

**Comment by alexraven1970** [comment]
[home-assistant_2024-07-28T11-03-39.551Z.log](https://github.com/user-attachments/files/16403023/home-assistant_2024-07-28T11-03-39.551Z.log)

Meinst Du das?

**Comment by littleyoda** [comment]
Hast du neben den Speedwire-Interface auch noch probeweise den Enneox-Interface getestet? Wenn ja, lösche bitte mal die Integration mit dem Enneox-Interface

Bist du dir bei den Zugangsdaten sicher?

Hast du sie schon mal im Sunny Explorer getestet?
https://www.sma.de/produkte/monitoring-control/sunny-explorer

**Comment by alexraven1970** [comment]
![Bildschirmfoto vom 2024-07-28 13-29-37](https://github.com/user-attachments/assets/5067a37d-42e7-466b-9eb9-5a5f8fa77e2f)
die drei hab ich versucht.
Bein PW bin ich mir sicher, web login funktioniert ja
![Bildschirmfoto vom 2024-07-28 13-31-54](https://github.com/user-attachments/assets/a0a9c3d5-afcd-47bd-ac04-bcda1421179f)

**Comment by alexraven1970** [comment]
ich seh nur ein interface

**Comment by alexraven1970** [comment]
![Bildschirmfoto vom 2024-07-28 13-33-27](https://github.com/user-attachments/assets/1bb656a0-bbef-48e4-bf5f-bf36145e9eb6)

**Comment by littleyoda** [comment]
Wenn du aber einen GUI-Zugriff hast, dann probiere bitte mal den Webconnect Zugang bei dir.

**Comment by alexraven1970** [comment]
![Bildschirmfoto vom 2024-07-28 14-01-14](https://github.com/user-attachments/assets/2f3023c0-cec9-48b6-b1f5-5bc1e0317f6b)

klappt nicht

**Comment by alexraven1970** [comment]
Terminal? 
ich kann es bedienen wenn ich die korreten Befehle habe ... :-)

**Comment by littleyoda** [comment]
Ich würde dich mal ein paar Tage vertrösten wollen.
Ich baue gerade eine Funktion ein, die nach SMA Geräten suchen kann und Information sammelt.
Damit kann ich dir dann hoffentlich besser helfen.

**Comment by littleyoda** [comment]
Hi

kannst du bitte mal auf die aktuelle Version 0.3.8 aktualisieren?

Danach unter Eintwicklerwerkzeuge/Dienste einmal den Discovery Service laufen lassen und das Ergebnisse hier posten. (Nachdem du ausführen geklickt hast, siehst du erst mal keine Veränderung. Die Ergebnisse kommen aber nach ca. 20 sekunden. Also einfach warten)
![grafik](https://github.com/user-attachments/assets/aa9b4685-6594-400a-ad4b-47f09899c4c4)

**Comment by alexraven1970** [comment]
Hi,
sorry für de Verzögerung, ich musste die letzten Tage ins Büro. Da fehlen die 3 Stunden Pendeln ... keine Freizeit mehr ... 

okay, update ist durch, keine Fehlermeldungen. Dann wollte ich den Dienst starten, finde nichts unter SMA. Hab den Beehl direkt eingegeben mit dem erwarteten Ergebnis
![grafik](https://github.com/user-attachments/assets/8db17b83-9530-4678-b9f5-6ac8fd4305f0)

**Comment by alexraven1970** [comment]
ich lade die repository gerade nochmal, noch ein HA restart, dann versuch ich es nochmal

**Comment by alexraven1970** [comment]
taucht in Dienste nicht auf. Und nun?

**Comment by littleyoda** [comment]
Kannst du mal unter Integrationen schauen, welche Version installiert ist?

Es sollte 3.8.1 sein.


[![Open your Home Assistant instance and show the system dashboard.](https://my.home-assistant.io/badges/integrations.svg)](https://my.home-assistant.io/redirect/integration/?domain=pysmaplus)

![grafik](https://github.com/user-attachments/assets/faa86b3d-365d-4fb3-968e-30f291ee8f20)

**Comment by alexraven1970** [comment]
![grafik](https://github.com/user-attachments/assets/bcc21dcb-95e8-4a6a-a1ca-536df9292ae6)

**Comment by alexraven1970** [comment]
den Integrationseintrag finde ich nur in HACS
über Einastellungen sehe ich keine Integration, nur Gerät und Entität

**Comment by littleyoda** [comment]
Füge bitte nochmal wie du schon oben probiert hattest, eine Integration zu. (selbst wenn sie nur einen Fehler zeigt) und probiere es dann nochmal.

**Comment by alexraven1970** [comment]
![grafik](https://github.com/user-attachments/assets/881664d9-7e84-4169-b227-34bbd899fc90)
![grafik](https://github.com/user-attachments/assets/941cef5f-b0fc-45a8-b29c-2eb81693d27a)

**Comment by alexraven1970** [comment]
soll ich erst die bestehende löschen?

**Comment by littleyoda** [comment]
Ich werde aus deinen Problemen leider nicht schlau.
Es kann sein (kann's gerade nicht testen), dass der Discovery-Service nur verfügbar ist, wenn auch ein Gerät angelegt ist. Ich dachte, es wäre unabhängig davon, ob die Integration laufen oder nicht laufen würde. Ist aber wohl nicht der Fall.
Dann muss ich die Tage nochmal die discovery-Funktion komplett umbauen.

**Comment by alexraven1970** [comment]
alles klar, danke dir

**Comment by littleyoda** [comment]
There is now a consolidated bug for the problems with Speedwire. #18
