### ISSUE TITLE
EV-Charger Error

### ISSUE THREAD

**Issue by Fischje** [littleyoda/ha-pysmaplus#17]
Used Version of Home Assistant: 2024.9.2
Used Version of ha-pysmaplus: 0.4.3

Looked at the Log at home-Assistant, see below.

Used Interface/Access Method

Speedwire: [ ]
Webconnect: [ ]
EnnexOS-based: [x ]
Energymeter/SHM2: [ ]

List of the integrated SMA devices
Inverter: STP 8.0
Sunny Home Manager 2

Screenshots and Diagnose Information

**Comment by Fischje** [comment]
pls delete, was false.

**Comment by Fischje** [comment]
Sry, se first edit at my start, but this is the real log entry:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: pysmaplus.device_ennexos
Quelle: custom_components/pysmaplus/__init__.py:126
Integration: SMA Devices Plus (Dokumentation, Probleme)
Erstmals aufgetreten: 12:26:12 (6 Vorkommnisse)
Zuletzt protokolliert: 14:26:26

Request to https://192.168.1.150/api/v1/measurements/live did not return a valid json. Code 401
Error requesting https://192.168.1.150/api/v1/featuretoggles [Timeout]

**Comment by Fischje** [comment]
<img width="492" alt="image" src="https://github.com/user-attachments/assets/42fa7889-d7da-41ce-a60f-70bce4bd61e9">

**Comment by littleyoda** [comment]
Den Fehler bzgl. featuretoggles kannst du ignorieren.

Die restlichen Entities kannst du einblenden,wenn du auf versteckte Enities klickst.
