### ISSUE TITLE
New type of SMA-inverters

### ISSUE THREAD

**Issue by frederikvoGIT** [littleyoda/ha-pysmaplus#2]
Hi Littleyoda,

I just want to let you know SMA is starting to distribute a new range of inverters running with Ennexos. (Sunny Boy Smart Energy)

I'm pretty new in the Github- and self-programming-world but wanted to notify you so you can maybe add it in your explanation.

I'm going to try your Pysmaplus next days. So keep fingers crossed.

Best regards,
Frederik

**Comment by littleyoda** [comment]
Thanks for the tip.

The integration behavior you described in the HA forum fits in perfectly with this
Please send me the diagnostic information. Then I should be able to integrate the support. 

For reference: 
https://community.home-assistant.io/t/support-for-more-sma-devices-e-g-tripower-x/713737/21

**Comment by littleyoda** [comment]
Thanks for your help [frederikvoGIT](https://github.com/frederikvoGIT)
