### ISSUE TITLE
POWER_VOLT_AMPERE_REACTIVE deprecated constant 

### ISSUE THREAD

**Issue by KimCarlsen** [littleyoda/ha-pysmaplus#21]
HA version 2024.10.2
ha-pysmaplus version 4.5.1

log:
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 12:36:58 (1 occurrences)
Last logged: 12:36:58

POWER_VOLT_AMPERE_REACTIVE was used from pysmaplus, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'pysmaplus' custom integration

**Comment by littleyoda** [comment]
fixed in v0.4.6
