### ISSUE TITLE
Is there a way to set the scan interval?

### ISSUE THREAD

**Issue by Grizzler89** [littleyoda/ha-pysmaplus#3]
Hi Littleyoda,

is it possible configure the scan interval? I would like to set it to 1 second.

Best regards

**Comment by littleyoda** [comment]
not yet

**Comment by littleyoda** [comment]
Implemented in 0.3.0

![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/279f3551-00c1-46a2-88fe-7d6c3ddd32db)
