### ISSUE TITLE
host SMA Solar device

### ISSUE THREAD

**Issue by menvis** [littleyoda/ha-pysmaplus#32]
I have access to the dashboard of "Zonneweide Glimmen" via my internet browser using the "SMA SUNNY PORTAL powered by ennexOS". I want to use the data via the HACS integration SMA Devices Plus in the Home Assistant. Then I select "SMA devices with EnnexOS". The integration then asks for "Host". What do I then have to fill in? Or does this integration not work in my case? See the screen shots.
![3](https://github.com/user-attachments/assets/91d85b67-2e1a-4d69-ac32-852da3331fa6)
![2](https://github.com/user-attachments/assets/b7555112-fb23-40e1-b733-14c12397c840)
![1](https://github.com/user-attachments/assets/a715807a-1a1c-4200-8bed-f9f424786c5f)

**Comment by littleyoda** [comment]
The Sunny Portal is not supported.
Devices that use the ennexos operating system are supported.

Are there any reasons why you are not adding the individual devices?

**Comment by menvis** [comment]
Thank you. I will try the individual devices.
