### ISSUE TITLE
Problem with all entity of inverter

### ISSUE THREAD

**Issue by vindiesel891** [littleyoda/ha-pysmaplus#4]
Hi,

nine Hours ago home Assistant show me this problem:
Can you see the attached Photo.
If I click on an entity i receive this message: this entity is no longer provided by the pysmaplus integration. 

![IMG_5482](https://github.com/littleyoda/ha-pysmaplus/assets/26111855/603ab4fb-d091-429d-a1f3-d4925a7581e1)

Can you risolve the problem please?
Thanks

**Comment by littleyoda** [comment]
Can you please send me the diagnose information?

https://littleyoda.github.io/

![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/d846162e-a0c8-4647-bff9-5d7ebf652a6a)

**Comment by vindiesel891** [comment]
With the smartphone i’m not able to download the diagnostic file. Is it
normal?
Thanks

Il giorno mer 12 giu 2024 alle 08:21 Sven ***@***.***> ha
scritto:

**Comment by vindiesel891** [comment]
This is the diagnostic file!

Il giorno mer 12 giu 2024 alle 09:34 Luca Altichieri ***@***.***>
ha scritto:

**Comment by littleyoda** [comment]
Unfortunately, the diagnostics function is probably defective in the current Home Assisant version. Since I can't do much without the information, we'll probably have to wait for a new, corrected version of HA.

If the historical data is not important, you can also try deleting the device and adding it again. Please make a backup first.

**Comment by ulrich379** [comment]
Morning, may be i have the same problem. If i make an reboot of the system (hoass), the network is confused. In the Logviewer i have this Message every 2 seconds: WARNING (Mainthread) (pymodbus.logging) Failed to connect. If i recover the backup made before restart everything is fine.

**Comment by littleyoda** [comment]
> Morning, may be i have the same problem. 
I created a new Issue because as this are probably different problems, as your problem occurs with Modbus (SHM2 with Grid Guard Code).

**Comment by littleyoda** [comment]
[vindiesel891](https://github.com/vindiesel891)
Can you try to create a diagnosic file f the problems persist?

**Comment by ulrich379** [comment]
Sorry, vor late answer. I have an X20 and an EMeter20, no SHM2.
I have an Diagnostic File downloaded after Restart.

Am Dienstag, Juli 09, 2024 09:26 CEST, schrieb Sven ***@***.***>:
 
 
vindiesel891
Can you try to create a diagnosic file f the problems persist?

**Comment by ulrich379** [comment]
I think In the first file debugging wos not aktivatet.

Greeting Ulrich Maurer

Am Dienstag, Juli 09, 2024 09:26 CEST, schrieb Sven ***@***.***>:
 
 
vindiesel891
Can you try to create a diagnosic file f the problems persist?

**Comment by littleyoda** [comment]
Can you please send me the diagnosic information bei Mail?
https://littleyoda.github.io/

Sending it to github via mail does not work.

**Comment by littleyoda** [comment]
This bug should be fixed by the last release
