### ISSUE TITLE
Modbus connection problems

### ISSUE THREAD

**Issue by littleyoda** [littleyoda/ha-pysmaplus#8]
Morning, may be i have the same problem. If i make an reboot of the system (hoass), the network is confused. In the Logviewer i have this Message every 2 seconds: WARNING (Mainthread) (pymodbus.logging) Failed to connect. If i recover the backup made before restart everything is fine.

_Originally posted by @ulrich379 in https://github.com/littleyoda/ha-pysmaplus/issues/4#issuecomment-2216707778_

**Comment by littleyoda** [comment]
I assume you are using the SHM2 with Grid Guard Code.

0. Please enable the debug logging

![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/da178c9f-e4f5-4faf-a7e8-f3c5e08c13c1)


2. Try to reload the integration

![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/c5e66365-6142-4166-8d91-8279a18e7d77)

3. Can you please test if you are able to connect to your inverter using a modbus program?
e.g. https://qmodbus.sourceforge.net/
Please you there config as shown in the screenshot. But change the IP-Address.
![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/9542fd20-d374-4e1e-8ccd-4f39dcb526f8)

**Comment by ulrich379** [comment]
I have a working Modbus Connection to the invererter:
modbus
 - name: sma_hub
    type: tcp
    host: 10.10.10.173
    port: 502
    sensors: !include sma_adresses.yaml
    delay: 0
    message_wait_milliseconds: 30
    timeout: 5
I have testet with deaktivatet modbus.yaml but the error persist.



Am Dienstag, Juli 09, 2024 09:18 CEST, schrieb Sven ***@***.***>:
 
 
I assume you are using the SHM2 with Grid Guard Code. * Please enable the debug logging
grafik.png (view on web) * Try to reload the integration
grafik.png (view on web) * Can you please test if you are able to connect to your inverter using a modbus program?
e.g. https://qmodbus.sourceforge.net/
Please you there config as shown in the screenshot. But change the IP-Address.
grafik.png (view on web)

**Comment by littleyoda** [comment]
You wrote:
> Sorry, vor late answer. I have an X20 and an EMeter20, no SHM2. 

I have just lost the overview.

Which interface are you using?

![grafik](https://github.com/littleyoda/ha-pysmaplus/assets/6692041/18c6f2a7-c788-4da6-8da4-17a89e988cad)

If you are not using "Sunny Home Manager 2 with Grid Guard Code", your problem has nothing to do with my integration.

The Energy Meter 2 does not support modbus, as far as I know.


We can also continue in german, if it is easier for you.

**Comment by ulrich379** [comment]
I use the ennexos interface

Am Dienstag, Juli 09, 2024 11:19 CEST, schrieb Sven ***@***.***>:
 
 
You wrote:
Sorry, vor late answer. I have an X20 and an EMeter20, no SHM2.
I have just lost the overview.
Which interface are you using?
grafik.png (view on web)
If you are not using "Sunny Home Manager 2 with Grid Guard Code", your problem has nothing to do with my integration.
The Energy Meter 2 does not support modbus, as far as I know.
We can also continue in german, if it is easier for you.
