### ISSUE TITLE
problem when no battery connected

### ISSUE THREAD

**Issue by bwynants** [littleyoda/ha-pysmaplus#9]
Used Version of Home Assistant: 2024.7.2
Used Version of ha-pysmaplus: 0.3.7

**Describe the bug, Remarks, ...**
I have no battery connected. This is what the log gives...

ValueError: Sensor sensor.sunny_boy_smart_energy_5_0_battery_current_a has device class 'current', state class 'measurement' unit 'A' and suggested precision '1' thus indicating it has a numeric value; however, it has the non-finite value: 'nan'

**Comment by littleyoda** [comment]
The message is a hint that you can actually ignore.
If the message annoys you, it is probably easiest to deactivate the sensor in

![grafik](https://github.com/user-attachments/assets/235f80e0-6b4f-46cf-83ee-f6da5a35f80a)

The effort required to automatically deactivate the sensor in the program is significantly greater then the manual approach. There are sensors that do not provide any values at night. Distinguishing between sensors that are only inactive at night and sensors that are always inactive would be too complex in the program.
